services:
  frontend:
    image: carlso/tattooar-frontend:latest
    ports:
      - "80:80"
    restart: always

  backend:
    image: carlso/tattooar-backend:latest
    env_file: ./env-backend/.env
    ports:
      - "4000:4000"
    restart: always